apps/emprestimo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('new-emprestimo/', views.confirm_emprestimo, name="new-emprestimo"),
    path('edit-emprestimo/<int:pk>', views.open_update_emprestimo, name="edit-emprestimo"),
    path('open-emprestimo/', views.open_update_emprestimo, name="open-emprestimo"),
    path('list-emprestimos/', views.list_emprestimos, name="list-emprestimo"),
    path('calc-emprestimo/', views.calc_emprestimo, name="calc-emprestimo"),
    path('detail-emprestimo/', views.detail_emprestimo, name="detail-emprestimo"),
    path('cobranca-diaria/', views.table_charge, name="cobranca-diaria"),
    path('update-payment/', views.update_status_payment, name="update-payment"),
    path('quitados/', views.emprestimos_quitados, name="emprestimos-quitados"),
    path('em-aberto/', views.list_emprestimo_em_aberto, name="emprestimos-em-aberto"),
    path('update-status-emprestimo/', views.update_status_emprestimo, name="update-status-emprestimo")
]

gestor/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.utils.views import login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.utils.urls', 'utils'), namespace='utils')),
    path('agiota/', include(('apps.agiota.urls', 'agiota'), namespace='agiota')),
    path('cliente/', include(('apps.cliente.urls', 'cliente'), namespace='cliente')),
    path('emprestimo/', include(('apps.emprestimo.urls', 'emprestimo'), namespace='emprestimo')),
]

apps/emprestimo/models.py
from django.db import models
from apps.cliente.models import Cliente
from . import choices
from apps.firma.models import Firma


class Emprestimo(models.Model):
    firma = models.ForeignKey(to=Firma, on_delete=models.DO_NOTHING, blank=True, null=True)
    cliente = models.ForeignKey(to=Cliente, on_delete=models.DO_NOTHING, blank=True, null=True)
    valor = models.CharField(max_length=6)
    juros = models.CharField(choices=choices.JUROS_CHOICES, max_length=3, default="1")
    parcela = models.CharField(choices=choices.PARCELAS_CHOICES, max_length=3, default="1")
    val_parcel = models.CharField(max_length=10, blank=True, null=True)
    vencimento = models.CharField(choices=choices.DIA_PAGAMENTO_CHOICES, max_length=3, default="1")
    num_parcela = models.CharField(max_length=10, blank=True,null=True)
    pagou_parcela = models.BooleanField(default=False)
    quitou = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    data = models.DateTimeField(auto_now_add=True)
    em_aberto = models.BooleanField(default=False)
    data_em_aberto = models.DateTimeField(blank=True, null=True)
    data_quitacao = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.cliente.first_name

    class Meta:
        verbose_name = "Empréstimo"
        verbose_name_plural = "Empréstimos"

apps/emprestimo/forms.py
from django import forms
from apps.cliente.models import Cliente
from .choices import JUROS_CHOICES, PARCELAS_CHOICES, DIA_PAGAMENTO_CHOICES
from .models import Emprestimo


class EmprestimoForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(
        required=False,
        label="Selecione o cliente",
        queryset=Cliente.objects.filter(is_active=True),
        widget=forms.Select(
            attrs={
                'class': 'form-control req'
            }
        )
    )

    valor = forms.CharField(
        required=False,
        label="Valor *",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control req'
            }
        )
    )

    juros = forms.ChoiceField(
        required=False,
        label="Selecione a Taxa de Juros (%) *",
        choices=JUROS_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control req'
            }
        )
    )

    parcela = forms.ChoiceField(
        required=False,
        label="Selecione Qtd. de parcelas *",
        choices=PARCELAS_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control req'
            }
        )
    )

    vencimento = forms.ChoiceField(
        required=False,
        label="Selecione o dia para vencimento da parcela",
        choices=DIA_PAGAMENTO_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control req'
            }
        )
    )

    class Meta:
        model = Emprestimo
        fields = [
            'cliente', 'valor', 'juros', 'parcela', 'vencimento'
        ]

apps/emprestimo/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from datetime import date, datetime
from . import models, forms


def confirm_emprestimo(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')

    response = {
        'success': False
    }

    if request.method == "POST":
        firma = request.user.firma
        cliente = request.POST.get('cliente')
        valor = request.POST.get('valor')
        juros = request.POST.get('juros')
        parcela = request.POST.get('parcela')
        vencimento = request.POST.get('vencimento')
        val_parcel = request.POST.get('val_parcel')
        pk = request.POST.get('pk_', None)

        if pk:
            edit_emprestimo = models.Emprestimo.objects.get(pk=pk)
            if edit_emprestimo:
                edit_emprestimo.valor = valor
                edit_emprestimo.juros = juros
                edit_emprestimo.num_parcela = parcela
                edit_emprestimo.parcela = parcela
                edit_emprestimo.vencimento = vencimento
                edit_emprestimo.val_parcel = val_parcel
                edit_emprestimo.firma = firma if firma else None
                edit_emprestimo.save()
                response = {
                    'success': True,
                    'edit': True
                }
        else:
            if cliente and valor and juros and parcela and vencimento:
                new_emprestimo = models.Emprestimo.objects.create(valor=valor, juros=juros, num_parcela=parcela,
                                                                  parcela=parcela, vencimento=vencimento,
                                                                  val_parcel=val_parcel, firma=firma if firma else None)
                new_emprestimo.cliente_id = int(cliente)
                print(val_parcel)
                new_emprestimo.save()
                response = {
                    'success': True
                }

    return JsonResponse(response, safe=True)


def open_update_emprestimo(request, pk=None):
    if not request.user.is_authenticated:
        return redirect('utils:login')

    page_title = "Abertura de Empréstimo" if not pk else "Editar Empréstimo"
    msg = None
    notification = None
    form = forms.EmprestimoForm()
    emprestimo = None

    if pk:
        emprestimo = models.Emprestimo.objects.filter(pk=pk, is_active=True)
        if emprestimo:
            emprestimo = emprestimo.last()
            form = forms.EmprestimoForm(instance=emprestimo)
        else:
            msg = "Nenhum Empréstimo encontrado!"
            notification = "danger"

    context = {
       'page_title': page_title, 'msg': msg, 'notification': notification,
        'form': form, 'emprestimo': emprestimo, 'pk_': pk
    }

    return render(request, 'cadastro_emprestimo.html', context)


def list_emprestimos(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')

    page_title = "Empréstimos Cadastrados"
    msg = None
    notification = None

    if request.user.is_superuser:
        emprestimos = models.Emprestimo.objects.filter(is_active=True).order_by('data')
    else:
        emprestimos = models.Emprestimo.objects.filter(is_active=True, firma=request.user.firma).order_by('data')

    if not emprestimos:
        msg = "Nenhum Empréstimo em Aberto"
        notification = "danger"

    context = {
        'page_title': page_title, 'msg': msg, 'notification': notification, 'emprestimos': emprestimos
    }

    return render(request, 'emprestimos_cadastrados.html', context)


@csrf_exempt
def calc_emprestimo(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')
    response = {
        'success': False
    }

    valor_inicial = request.POST.get('valor')
    juros = request.POST.get('juros')
    meses = request.POST.get('parcela')

    if juros and meses and valor_inicial:
        juros = int(juros)
        meses = int(meses)
        valor_inicial = int(valor_inicial)

        juros = juros / 100

        x = ((1+juros)**meses)-1
        y = (juros*((1+juros)**meses))

        percentual = x/y
        parcela = valor_inicial / percentual
        valor_total = parcela * meses
        valor_juros = valor_total - valor_inicial

        response = {
            'success': True,
            'parcela': parcela,
            'valor_total': valor_total,
            'valor_juros': valor_juros,
        }

    return JsonResponse(response, safe=False)


@csrf_exempt
def detail_emprestimo(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')
    response = {
        'success': False
    }

    if request.method == "POST":

        pk = request.POST.get('pk')
        if pk:

            emprestimo = models.Emprestimo.objects.get(pk=pk)

            if emprestimo:

                taxa_juros = emprestimo.juros
                meses = emprestimo.parcela
                valor_inicial = emprestimo.valor
                cliente = emprestimo.cliente.first_name

                if meses and taxa_juros and valor_inicial:
                    meses = int(meses)
                    taxa_juros = int(taxa_juros)
                    valor_inicial = int(valor_inicial)

                    juros = int(taxa_juros) / 100

                    x = ((1+juros)**meses)-1
                    y = (juros*((1+juros)**meses))

                    percentual = x/y
                    parcela = valor_inicial / percentual
                    valor_total = parcela * meses
                    valor_juros = valor_total - valor_inicial
                    qtd_parcela = valor_total/parcela

                    response = {
                        'success': True,
                        'valor_inicial': valor_inicial,
                        'valor_parcela': parcela,
                        'cliente': cliente,
                        'valor_total': valor_total,
                        'valor_juros': valor_juros,
                        'taxa_juros': taxa_juros,
                        'qtd_parcela': qtd_parcela,
                    }

    return JsonResponse(response, safe=False)


def table_charge(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')
    page_title = "Tabela de Cobrança"
    today = date.today()
    msg = None
    notification = None

    if request.user.is_superuser:
        emprestimos = models.Emprestimo.objects.filter(is_active=True, vencimento=today.day, pagou_parcela=False,
                                                       quitou=False)
    else:
        emprestimos = models.Emprestimo.objects.filter(is_active=True, vencimento=today.day, pagou_parcela=False,
                                                       quitou=False,  firma=request.user.firma)

    if not emprestimos:
        msg = "Nenhum pagamento para receber hoje!"
        notification = "danger"

    context = {
        'page_title': page_title, 'emprestimos': emprestimos, 'msg': msg, 'notification': notification
    }

    return render(request, 'cobranca_diaria.html', context)


@csrf_exempt
def update_status_payment(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')

    response = {'success': False}

    if request.method == 'POST':
        pk = request.POST.get('pk')

        if pk:
            emprestimo = models.Emprestimo.objects.get(pk=pk)
            if emprestimo:
                emprestimo.pagou_parcela = True
                parcelas_restante = int(emprestimo.num_parcela)
                if parcelas_restante == 1:
                    emprestimo.quitou = True
                    emprestimo.data_quitacao = datetime.now()
                    response['quitou'] = True
                else:
                    parcelas_restante -= 1
                    emprestimo.num_parcela = parcelas_restante
                    response['success'] = True
                emprestimo.save()

    return JsonResponse(response, safe=False)


def emprestimos_quitados(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')

    page_title = "Empréstimos Quitados"
    notification = None
    msg = None

    if request.user.is_superuser:
        emprestimos = models.Emprestimo.objects.filter(is_active=True, quitou=True)
    else:
        emprestimos = models.Emprestimo.objects.filter(is_active=True, quitou=True, firma=request.user.firma)

    if not emprestimos:
        msg = "Nenhum Empréstimo Quitado!"
        notification = "danger"

    context = {
        'page_title': page_title, 'emprestimos': emprestimos, 'msg': msg, 'notification': notification
    }
    return render(request, 'emprestimos_quitados.html', context)


@csrf_exempt
def update_status_emprestimo(request):
    response = {
        'success': False
    }

    if request.method == 'POST':
        pk = request.POST.get('pk')

        if pk:
            emprestimo = models.Emprestimo.objects.get(pk=pk)

            if emprestimo:
                emprestimo.em_aberto = True
                emprestimo.data_em_aberto = datetime.now()
                emprestimo.save()

                response['success'] = True
    return JsonResponse(response, safe=False)


def list_emprestimo_em_aberto(request):
    page_title = 'Parcela em Atraso'

    emprestimos = models.Emprestimo.objects.filter(is_active=True, em_aberto=True)

    context = {
        'page_title': page_title, 'emprestimos': emprestimos
    }

    return render(request, 'emprestimos_em_aberto.html', context)

apps/emprestimo/templates/cadastro_emprestimo.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
{% if notification and msg %}
<div class="row">
    <div class="col">
        <div class="alert alert-{{notification}}"><i class="fas fa-bell"></i>
            {{msg}}
        </div>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            <form class="form-horizontal form-material" id="form-emp" method="POST">
                <div class="form-group">
                    {% csrf_token %}
                    {% for i in form %}
                    <label class="col-md-12">{{ i.label }}</label>
                    <div class="col-md-12">
                        {{ i }}
                    </div>
                    <br>
                    {% if emprestimo %}
                        <input type="hidden" class="cls-pk" value="{{pk_}}">
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="col">
                    <a class="btn btn-primary text-white" id="btn-calcular">CALCULAR <i class="fas fa-check-square"></i></a>
                </div>
            </form>
        </div>
        <!--        {% if not pk %}-->
        <!--            <div class="row">-->
        <!--                <div class="col">-->
        <!--                    <div class="white-box">-->
        <!--                        <div class="col-md-4 col-sm-4 text-left">-->
        <!--                            <h3>Clientes ativos:</h3>-->
        <!--                        </div>-->
        <!--                    </div>-->
        <!--                </div>-->
        <!--                <div class="col">-->
        <!--                    <div class="white-box">-->
        <!--                        <div class="col-md-4 col-sm-4 text-left">-->
        <!--                            <h3>Status:</h3>-->
        <!--                        </div>-->
        <!--                    </div>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--        {% endif  %}-->
    </div>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'js/emprestimo/emprestimo.js' %}"></script>
{% endblock %}

apps/emprestimo/templates/cobranca_diaria.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
{% include 'alerts/alerts.html' %}
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <div class="table-responsive">
                <table class="table text-center">
                    <thead>
                    <tr>
                        <th>Ações</th>
                        <th>Cliente</th>
                        <th>Valor Inicial</th>
                        <th>Valor da Parcela</th>
                        <th>Parcelas Restantes</th>
                        <th>Telefone</th>
                    </tr>
                    </thead>
                    {% for i in emprestimos %}
                    <tbody>
                    <tr>
                        <td>
                            <div class="btn-group">
                                <button class="btn btn-primary btn-aberto" pk="{{ i.pk }}"><i class="fas fa-box"></i></button>
                                <button class="btn btn-warning btn-pagou" pk="{{ i.pk }}"><i class="far fa-calendar-check"></i></button>
                                <a class="btn btn-success" target="_blank" href="https://api.whatsapp.com/send?phone=+55{{i.cliente.celular_cliente}}"><i class="fab fa-whatsapp text-white"></i></a>
                            </div>
                        </td>
                        <td>{{ i.cliente.first_name }}</td>
                        <td>R$: {{ i.valor }},00</td>
                        <td>R$: {{ i.val_parcel }},00</td>
                        <td>{{i.num_parcela}}/{{i.parcela}}</td>
                        <td>{{ i.cliente.celular_cliente}}</td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/emprestimo/emprestimo.js' %}"></script>
{% endblock %}tml>

apps/emprestimo/templates/emprestimos_cadastrados.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
{% include 'alerts/alerts.html' %}
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Ações</th>
                        <th>Cliente</th>
                        <th>Valor Inicial</th>
                        <th>Taxa (%)</th>
                        <th>Data</th>
                    </tr>
                    </thead>
                    {% for i in emprestimos %}
                    <tbody>
                    <tr>
                        <td>
                            <div class="btn-group-sm btn-group" data-toggle="buttons">
                                <a class="btn btn-success" href="{% url 'emprestimo:edit-emprestimo' i.pk %}"><i class="fas fa-pencil-alt text-white"></i></a>
                                <button class="btn btn-primary btn-detail" value="{{ i.pk }}"><i class="fas fa-eye"></i></button>
                            </div>
                        </td>
                        <td>{{ i.cliente.first_name }}</td>
                        <td>R$: {{ i.valor }},00</td>
                        <td>{{ i.get_juros_display }}%</td>
                        <td>{{ i.data }}</td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/emprestimo/emprestimo.js' %}"></script>
{% endblock %}

apps/emprestimo/templates/emprestimos_em_aberto.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
{% include 'alerts/alerts.html' %}
<div class="row">
    <div class="col">
        <div class="white-box">
            <div class="table-responsive">
                <table class="table text-center">
                    <thead>
                    <tr>
                        <th>Cliente</th>
                        <th>Valor Inicial</th>
                        <th>Taxa (%)</th>
                        <th>Parcelas</th>
                        <th>Data</th>
                    </tr>
                    </thead>
                    {% for i in emprestimos %}
                    <tbody>
                    <tr>
                        <td>{{ i.cliente.first_name }}</td>
                        <td>R$: {{ i.valor }},00</td>
                        <td>{{ i.get_juros_display }}%</td>
                        <td>{{i.num_parcela}}/{{i.parcela}}</td>
                        <td>{{ i.data_em_aberto }}</td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/emprestimo/emprestimo.js' %}"></script>
{% endblock %}

apps/emprestimo/templates/emprestimos_quitados.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
{% include 'alerts/alerts.html' %}
<div class="row">
    <div class="col">
        <div class="white-box">
            <div class="table-responsive">
                <table class="table text-center">
                    <thead>
                    <tr>
                        <th>Cliente</th>
                        <th>Valor Inicial</th>
                        <th>Taxa (%)</th>
                        <th>Data</th>
                    </tr>
                    </thead>
                    {% for i in emprestimos %}
                    <tbody>
                    <tr>
                        <td>{{ i.cliente.first_name }}</td>
                        <td>R$: {{ i.valor }},00</td>
                        <td>{{ i.get_juros_display }}%</td>
                        <td>{{ i.data_quitacao }}</td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/emprestimo/emprestimo.js' %}"></script>
{% endblock %}