apps/cliente/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create-cliente/', views.create_update_cliente, name="create-cliente"),
    path('edit-cliente/<int:pk>', views.create_update_cliente, name="edit-cliente"),
    path('list-clientes/', views.list_clientes, name="list-clientes"),
    path('delete-cliente/', views.delete_cliente, name="delete-cliente")
]

gestor/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.utils.views import login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.utils.urls', 'utils'), namespace='utils')),
    path('agiota/', include(('apps.agiota.urls', 'agiota'), namespace='agiota')),
    path('cliente/', include(('apps.cliente.urls', 'cliente'), namespace='cliente')),
    path('emprestimo/', include(('apps.emprestimo.urls', 'emprestimo'), namespace='emprestimo')),
]

apps/cliente/models.py
from django.db import models
from apps.agiota.models import Agiota


class Cliente(Agiota):
    agiota = models.ForeignKey(to=Agiota, related_name="agiota_cliente", on_delete=models.DO_NOTHING, null=True)
    status = models.BooleanField(default=False)
    rg = models.CharField(max_length=15)
    cpf = models.CharField(max_length=15)
    celular_cliente = models.CharField(max_length=15)
    cep = models.CharField(max_length=15)
    endereco = models.CharField(max_length=200)
    nome_ref = models.CharField(max_length=50)
    rua_ref = models.CharField(max_length=50)
    num_ref = models.CharField(max_length=5)

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

apps/cliente/forms.py
from django import forms
from .models import Cliente
from apps.agiota.models import Agiota


class ClienteForm(forms.ModelForm):
    agiota = forms.ModelChoiceField(
        label="Selecione um Agiota",
        queryset=Agiota.objects.filter(is_active=True),
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    first_name = forms.CharField(
        label="Primeiro nome",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o primeiro nome aqui:'
            }
        )
    )

    last_name = forms.CharField(
        label="Sobrenome",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o sobrenome aqui:'
            }
        )
    )

    email = forms.CharField(
        label="E-mail",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira e-mail aqui:'
            }
        )
    )

    rg = forms.CharField(
        label="RG",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o rg aqui:'
            }
        )
    )

    cpf = forms.CharField(
        label="CPF",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o CPF aqui:'
            }
        )
    )

    celular_cliente = forms.CharField(
        label="Celular",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o celular aqui:'
            }
        )
    )

    cep = forms.CharField(
        label="CEP",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o CEP aqui:'
            }
        )
    )

    nome_ref = forms.CharField(
        label="Nome da referência",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o nome aqui:'
            }
        )
    )

    celular_ref = forms.CharField(
        label="Celular da referência",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o celular aqui:'
            }
        )
    )

    rua_ref = forms.CharField(
        label="Rua",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira a rua aqui:'
            }
        )
    )

    num_ref = forms.CharField(
        label="Número",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o número da casa aqui:'
            }
        )
    )

    class Meta:
        model = Cliente
        fields = [
            'agiota', 'first_name', 'last_name', 'email', 'rg', 'cpf', 'celular_cliente', 'cep', 'nome_ref', 'rua_ref',
            'num_ref', 'celular_ref'
        ]


class ClienteAgiotaForm(forms.ModelForm):
    first_name = forms.CharField(
        label="Primeiro nome",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o primeiro nome aqui:'
            }
        )
    )

    last_name = forms.CharField(
        label="Sobrenome",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o sobrenome aqui:'
            }
        )
    )

    email = forms.CharField(
        label="E-mail",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira e-mail aqui:'
            }
        )
    )

    rg = forms.CharField(
        label="RG",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o rg aqui:'
            }
        )
    )

    cpf = forms.CharField(
        label="CPF",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o CPF aqui:'
            }
        )
    )

    celular_cliente = forms.CharField(
        label="Celular",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o celular aqui:'
            }
        )
    )

    cep = forms.CharField(
        label="CEP",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o CEP aqui:'
            }
        )
    )

    nome_ref = forms.CharField(
        label="Nome da referência",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o nome aqui:'
            }
        )
    )

    celular_ref = forms.CharField(
        label="Celular da referência",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o celular aqui:'
            }
        )
    )

    rua_ref = forms.CharField(
        label="Rua",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira a rua aqui:'
            }
        )
    )

    num_ref = forms.CharField(
        label="Número",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Insira o número da casa aqui:'
            }
        )
    )

    class Meta:
        model = Cliente
        fields = [
            'first_name', 'last_name', 'email', 'rg', 'cpf', 'celular_cliente', 'cep', 'nome_ref', 'rua_ref',
            'num_ref', 'celular_ref'
        ]

apps/cliente/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from . import models, forms


def create_update_cliente(request, pk=None):
    if not request.user.is_authenticated:
        return redirect('utils:login')

    firma = request.user.firma.pk
    page_title = "Cadastrar Cliente" if not pk else "Editar Cliente"
    form = forms.ClienteForm() if not firma else forms.ClienteAgiotaForm()
    msg = None
    notification = None
    cliente = None

    if pk:
        cliente = models.Cliente.objects.filter(pk=pk)
        if cliente:
            cliente = cliente.last()
            form = forms.ClienteForm(instance=cliente) if not firma else forms.ClienteAgiotaForm(instance=cliente)
        else:
            msg = "Nenhum Cliente Encontrado!"
            notification = 'danger'
    if request.method == "POST":
        if cliente:
            form = forms.ClienteForm(request.POST, instance=cliente)\
                if not firma else forms.ClienteAgiotaForm(request.POST, instance=cliente)
        else:
            form = forms.ClienteForm(request.POST)\
                if not firma else forms.ClienteAgiotaForm(request.POST)

        try:
            if form.is_valid():
                if cliente:
                    cliente.save()
                    msg = "Cadastro Atualizado com Sucesso!"
                    notification = 'success'
                else:
                    if firma:
                        new_cliente = form.save(commit=False)
                        new_cliente.firma_id = firma
                        new_cliente.username = new_cliente.email
                        new_cliente.save()
                        msg = "Cliente cadastrado com Sucesso!"
                        notification = 'success'
            else:
                print(form.errors)
        except Exception as e:
            msg = e
            notification = 'warning'

        form = forms.ClienteForm() if not firma else forms.ClienteAgiotaForm()

    context = {
        'page_title': page_title, 'form': form, 'msg': msg, 'notification': notification
    }

    return render(request, 'cadastro_cliente.html', context)


def list_clientes(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')
    page_title = "Clientes Cadastrados"
    msg = None
    notification = None

    if request.user.is_superuser:
        clientes = models.Cliente.objects.filter(is_active=True)
    else:
        clientes = models.Cliente.objects.filter(is_active=True, firma=request.user.firma)

    if not clientes:
        msg = "Nenhum cliente Cadastrado!"
        notification = 'danger'

    context = {
        'page_title': page_title, 'clientes': clientes, 'msg': msg, 'notification': notification
    }

    return render(request, 'clientes_cadastrados.html', context)


@csrf_exempt
def delete_cliente(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')
    response = {
        'success': False
    }

    if request.method == 'POST':
        pk = request.POST.get('pk')

        if pk:
            cliente = models.Cliente.objects.get(pk=pk)
            if cliente:
                cliente.is_active = False
                cliente.save()
                response['success'] = True
    return JsonResponse(response, safe=False)

apps/cliente/templates/cadastro_cliente.html
{% extends 'base/base.html' %}
{% block content %}
{% if notification and msg %}
<div class="row">
    <div class="col">
        <div class="alert alert-{{notification}}"><i class="fas fa-bell"></i>
            {{msg}}
        </div>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            <form class="form-horizontal form-material" method="POST">
                {% csrf_token %}
                {% for i in form %}
                <div class="form-group">
                    <label class="col-md-12">{{ i.label }}</label>
                    <div class="col-md-12">
                        {{ i }}
                    </div>
                </div>
                {% endfor %}
                <div class="col">
                    <button type="submit" class="btn btn-success text-white">{% if pk %}SALVAR ALTERAÇÕES{% else %}CADASTRAR{% endif %} <i class="fas fa-check-square"></i></button>
                </div>
            </form>
        </div>
<!--        {% if not pk %}-->
<!--            <div class="row">-->
<!--                <div class="col">-->
<!--                    <div class="white-box">-->
<!--                        <div class="col-md-4 col-sm-4 text-left">-->
<!--                            <h3>Clientes ativos:</h3>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col">-->
<!--                    <div class="white-box">-->
<!--                        <div class="col-md-4 col-sm-4 text-left">-->
<!--                            <h3>Status:</h3>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        {% endif  %}-->
    </div>
</div>
{% endblock %}

apps/cliente/templates/clientes_cadastrados.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
{% include 'alerts/alerts.html' %}
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Ações</th>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>RG</th>
                        <th>CPF</th>
                    </tr>
                    </thead>
                    {% for i in clientes %}
                    <tbody>
                    <tr>
                        <td>
                            <div class="btn-group-sm btn-group" data-toggle="buttons">
                                <a class="btn btn-success" href="{% url 'cliente:edit-cliente' i.pk %}" name="options"><i class="fas fa-pencil-alt text-white"></i></a>
                                <button class="btn btn-danger btn-trash" value="{{ i.pk }}"><i class="fas fa-trash text-white"></i></button>
                            </div>
                        </td>
                        <td>{{ i.first_name }} {{ i.last_name }}</td>
                        <td>{{ i.email }}</td>
                        <td>{{ i.rg }}</td>
                        <td>{{ i.cpf }}</td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/cliente/cliente.js' %}"></script>
{% endblock %}