apps/agiota/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('list-agiota/', views.list_agiotas, name="list_agiotas"),
    path('new-agiota/', views.create_update_agiota, name="new_agiota"),
    path('edit-agiota/<int:pk>', views.create_update_agiota, name="edit_agiota"),
]

apps/cliente/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create-cliente/', views.create_update_cliente, name="create-cliente"),
    path('edit-cliente/<int:pk>', views.create_update_cliente, name="edit-cliente"),
    path('list-clientes/', views.list_clientes, name="list-clientes"),
    path('delete-cliente/', views.delete_cliente, name="delete-cliente")
]

apps/emprestimo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('new-emprestimo/', views.confirm_emprestimo, name="new-emprestimo"),
    path('edit-emprestimo/<int:pk>', views.open_update_emprestimo, name="edit-emprestimo"),
    path('open-emprestimo/', views.open_update_emprestimo, name="open-emprestimo"),
    path('list-emprestimos/', views.list_emprestimos, name="list-emprestimo"),
    path('calc-emprestimo/', views.calc_emprestimo, name="calc-emprestimo"),
    path('detail-emprestimo/', views.detail_emprestimo, name="detail-emprestimo"),
    path('cobranca-diaria/', views.table_charge, name="cobranca-diaria"),
    path('update-payment/', views.update_status_payment, name="update-payment"),
    path('quitados/', views.emprestimos_quitados, name="emprestimos-quitados"),
    path('em-aberto/', views.list_emprestimo_em_aberto, name="emprestimos-em-aberto"),
    path('update-status-emprestimo/', views.update_status_emprestimo, name="update-status-emprestimo")
]

apps/utils/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login/', views.acesso, name="login"),
    path('logout/', views.logout_, name="logout"),
]

gestor/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.utils.views import login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.utils.urls', 'utils'), namespace='utils')),
    path('agiota/', include(('apps.agiota.urls', 'agiota'), namespace='agiota')),
    path('cliente/', include(('apps.cliente.urls', 'cliente'), namespace='cliente')),
    path('emprestimo/', include(('apps.emprestimo.urls', 'emprestimo'), namespace='emprestimo')),
]

apps/utils/models.py
from django.db import models

# Create your models here.

apps/utils/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import logout_then_login
from django.shortcuts import render, redirect
from apps.agiota import models


def dashboard(request):
    if not request.user.is_authenticated:
        return redirect('utils:login')

    page_title = 'Dashboard'

    context = {
        'page_title': page_title
    }
    return render(request, 'dashboard/dashboard.html', context)


def acesso(request):
    if request.user.is_authenticated:
        return redirect('utils:dashboard')

    erro = False
    msg = None
    pagamento = True
    notification = None

    if request.method == 'POST':
        email = request.POST.get('email', None)
        senha = request.POST.get('senha', None)

        if email:
            pagamento = models.Agiota.objects.filter(email=email)
            if pagamento:
                pagamento = pagamento.last()
                if pagamento.pagou:
                    user = authenticate(username=email, password=senha)

                    if user:
                        login(request, user)
                        return redirect('utils:dashboard')
                    else:
                        notification = 'danger'
                        msg = 'Usuário ou senha inválidos!'
                else:
                    notification = 'danger'
                    msg = 'Pagamento não identificado! Entre em contato com o suporte!'
    context = {
        'erro': erro, 'msg': msg, 'notification': notification
    }
    return render(request, 'login/login.html', context)


def logout_(request):
    return logout_then_login(request, login_url='/login')

apps/utils/templates/barras/navbar.html
{% load static %}
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin6">
<!--                <a class="navbar-brand" href="dashboard.html">-->
<!--                    <span class="logo-text">-->
<!--                                <img src="{% static 'plugins/images/logo-1.jpg' %}" alt="homepage" />-->
<!--                            </span>-->
<!--                </a>-->
            <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
               href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <ul class="navbar-nav d-none d-md-block d-lg-none">
                <li class="nav-item">
                    <a class="nav-toggler nav-link waves-effect waves-light text-white"
                       href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

apps/utils/templates/barras/sidebar.html
<aside class="left-sidebar" data-sidebarbg="skin6">
    <div class="scroll-sidebar">
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item pt-2">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'utils:dashboard' %}"
                       aria-expanded="false">
                        <i class="fas fa-chart-area" aria-hidden="true"></i>
                        <span class="hide-menu">Painel</span>
                    </a>
                </li>
                {% if request.user.is_superuser %}
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'agiota:new_agiota' %}"
                           aria-expanded="false">
                            <i class="fas fa-user" aria-hidden="true"></i>
                            <span class="hide-menu">Cadastro de Agiota</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'agiota:list_agiotas' %}"
                           aria-expanded="false">
                            <i class="fas fa-users" aria-hidden="true"></i>
                            <span class="hide-menu">Agiotas Cadastrados</span>
                        </a>
                    </li>
                {% endif %}
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'cliente:create-cliente' %}"
                       aria-expanded="false">
                        <i class="fas fa-users" aria-hidden="true"></i>
                        <span class="hide-menu">Cadastro de Cliente</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'cliente:list-clientes' %}"
                       aria-expanded="false">
                        <i class="fas fa-clipboard-list" aria-hidden="true"></i>
                        <span class="hide-menu">Clientes Cadastrados</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'emprestimo:list-emprestimo' %}"
                       aria-expanded="false">
                        <i class="far fa-money-bill-alt" aria-hidden="true"></i>
                        <span class="hide-menu">Empréstimos Cadastrados</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'emprestimo:emprestimos-em-aberto' %}"
                       aria-expanded="false">
                        <i class="far fa-money-bill-alt" aria-hidden="true"></i>
                        <span class="hide-menu">Parcelas em Atraso</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'emprestimo:emprestimos-quitados' %}"
                       aria-expanded="false">
                        <i class="fas fa-calendar-check" aria-hidden="true"></i>
                        <span class="hide-menu">Emprestimos Quitados</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'emprestimo:cobranca-diaria' %}"
                       aria-expanded="false">
                        <i class="fas fa-calendar" aria-hidden="true"></i>
                        <span class="hide-menu">Tabela de Cobrança</span>
                    </a>
                </li>
                <li class="text-center p-20 upgrade-btn">
                    <a href="{% url 'emprestimo:open-emprestimo' %}"
                       class="btn btn-block btn-success text-white">
                        <i class="far fa-money-bill-alt" aria-hidden="true"></i>
                        Abertura de Empréstimo
                    </a>
                    <a href="{% url 'utils:logout' %}"
                       class="btn btn-block btn-danger text-white">
                        <i class="fa fa-power-off" aria-hidden="true"></i>
                        Encerrar Sessão
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>